// frontend-resume/src/lib/components/Footer/Footer.svelte
<script lang="ts">
    import { personal } from '$content';
    import { links } from '$lib/config/links';
    import { fullName } from '$lib/helpers/utils';
    import ButtonLink from '$lib/components/Button/ButtonLink.svelte';

    const currentYear = new Date().getFullYear();
</script>

<footer class="bg-neutral-3 mt-12 py-2 text-neutral-12">
    <div class="container text-center">
        {#if links && links.length > 0}
            <div class="flex justify-center">
                <div class="grid grid-flow-col gap-2">
                    {#each links as link (link.title)}
                        <ButtonLink
                                class="h-12 w-12 rounded-full p-0"
                                href={link.href}
                        >
              <span class="sr-only">
                {personal.givenName} on {link.title}
              </span>
                            <svelte:component this={link.icon} aria-hidden size={18} />
                        </ButtonLink>
                    {/each}
                </div>
            </div>
        {/if}

        <div class="mt-6">
            Copyright ©{currentYear} {fullName}
        </div>

        <div class="mt-1 text-sm">
          This resume was generated with <a class="link" href="https://svelte.dev/">SvelteKit</a> and deployed on <a class="link" href="https://aws.amazon.com/">AWS</a>.
        </div>
    </div>
</footer>

// frontend-resume/src/components/Footer/Footer.tsx
import { personal } from '@content';
import { links } from 'edit-me/config/links';
import React from 'react';
import { fullName } from 'src/helpers/utils';
import ButtonLink from '../Button/ButtonLink';

export const Footer: React.FC = () => {
  return (
    <footer className="mt-12 bg-neutral-3 py-12 text-neutral-12">
      <div className="container text-center">
        {links && (
          <div className="flex justify-center">
            <div className="grid grid-flow-col gap-2">
              {links.map((link) => (
                <ButtonLink
                  className="h-12 w-12 rounded-full p-0"
                  href={link.href}
                  key={link.title}
                >
                  <span className="sr-only">
                    {personal.givenName} on {link.title}
                  </span>
                  <link.icon aria-hidden size={18} />
                </ButtonLink>
              ))}
            </div>
          </div>
        )}

        <div className="mt-6">
          Copyright ©{new Date().getFullYear()} {fullName}
        </div>

        <div className="mt-1 text-sm">
          This resume was generated with{' '}
          <a className="link" href="https://nextjs.org/">
            Next.js
          </a>{' '}
          and deployed on{' '}
          <a className="link" href="https://aws.amazon.com/lightsail/">
            AWS Lightsail
          </a>
          . Learn how to deploy your own resume with the{' '}
          <a
            className="link"
            href="https://github.com/ElijahCra/Resume-WebStack"
          >
            Resume Webstack
          </a>
          !
        </div>
      </div>
    </footer>
  );
};
