// frontend-resume/src/components/Articles/ProfessionalItem.tsx
import { ProfessionalExperience } from '@content';
import { CalendarIcon } from '@heroicons/react/24/solid';
import React from 'react';
import { Heading } from '../Heading/Heading';
import Prose from '../Prose/Prose';

const ProfessionalItem: React.FC<ProfessionalExperience> = ({
  body,
  endDate,
  organization,
  startDate,
  title,
}) => {
  return (
    <article className="border-t-2 border-neutral-6 py-6 first-of-type:border-none last-of-type:pb-0">
      <Heading className="text-balance" level={3}>
        <span className="rounded-md bg-neutral-12 px-2 text-neutral-1">
          {title}
        </span>
        <span> at {organization}</span>
      </Heading>

      <div className="mt-1 flex items-center gap-2 font-medium tracking-wide">
        <CalendarIcon className="inline h-6" />
        {startDate}–{!endDate ? 'Current' : endDate}
      </div>

      <Prose
          html={body.html}
          className="prose-ul:list-disc prose-ul:pl-5 prose-li:mb-2"
      />
    </article>
  );
};

export default ProfessionalItem;

// frontend-resume/src/lib/components/Articles/ProfessionalItem.svelte
<script lang="ts">
    import { Calendar } from 'lucide-svelte';
    import Heading from '$lib/components/Heading/Heading.svelte';
    import Prose from '$lib/components/Prose/Prose.svelte';

    import type { Component } from 'svelte';

    let { component, endDate, organization, startDate, title }: {
        component: Component;
        endDate?: string;
        organization: string;
        startDate: string;
        title: string;
    } = $props();
</script>

<article class="first-of-type:mt-10">
    <Heading class="text-balance" level={3}>
        <span class="rounded-md bg-neutral-12 px-2 text-neutral-1">
            {title}
        </span>
        <span> at {organization}</span>
    </Heading>

    <div class="mt-1 flex items-center gap-2 font-medium tracking-wide">
        <Calendar class="inline h-6 w-6" />
        {startDate}–{!endDate ? 'Current' : endDate}
    </div>

    <Prose {component} />
</article>
