// frontend-resume/src/lib/components/Articles/Skills.svelte
<script lang="ts">
    import { allSkills } from '$content';
    import { Check } from 'lucide-svelte';
    import Heading from '$lib/components/Heading/Heading.svelte';
    import Prose from '$lib/components/Prose/Prose.svelte';
    import SectionHeading from '$lib/components/SectionHeading/SectionHeading.svelte';
</script>

<article>

        <SectionHeading
                Icon={Check}
                level={3}
                text="Skills & Expertise"
        />

    <div class="grid grid-flow-row gap-6 lg:grid-flow-col">
        {#each allSkills as skill (skill._id)}
            <div>
                <Heading level={4}>
                    <div class="flex items-center gap-2">
                        {skill.title}
                    </div>
                </Heading>

                <Prose class="text-neutral-11" component={skill.component} />
            </div>
        {/each}
    </div>
</article>

// frontend-resume/src/components/Articles/Skills.tsx
import { allSkills } from '@content';
import { CheckIcon } from '@heroicons/react/24/solid';
import React from 'react';
import { Heading } from '../Heading/Heading';
import Prose from '../Prose/Prose';
import { SectionHeading } from '../SectionHeading/SectionHeading';

const Skills: React.FC = () => {
  return (
    <article>
      <SectionHeading
        Icon={CheckIcon}
        level={3}
        text="Skills &amp; Expertise"
      />

      <div className="mt-2 grid grid-flow-row gap-6 lg:grid-flow-col">
        {allSkills.map((skill) => (
          <div key={skill._id}>
            <Heading level={4}>
              <div className="flex items-center gap-2">
                {skill.title}
              </div>
            </Heading>

            <Prose className="text-neutral-11" html={skill.body.html} />
          </div>
        ))}
      </div>
    </article>
  );
};

export default Skills;
